### PR TITLE
Final Capstone Projects

### PR DESCRIPTION
**Pull request by MICHAELMUNAVU83**
- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write integration tests with a React testing library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions and reducers in React.

### CODE REVIEW

**Review by muneebulrehman — COMMENTED** [review]
Hi @MICHAELMUNAVU83 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses GitHub flow instead of git-flow.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by MICHAELMUNAVU83** [comment]
@muneebulrehman Hello, I hope you are doing well .I used the same method I have been using for git-flow projects , I made the dev branch default and worked on feature branches then later created a pull request between the master and dev. Kindly advise .

**Comment by muneebulrehman** [comment]
> @muneebulrehman Hello, I hope you are doing well .I used the same method I have been using for git-flow projects , I made the dev branch default and worked on feature branches then later created a pull request between the master and dev. Kindly advise .

Hey @MICHAELMUNAVU83, in git-flow, you should submit a PR from a branch( preferably name it features ) into the dev branch.

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @MICHAELMUNAVU83,** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## **Invalid Code Review Request**

You have submitted a project, that _**As the previews, CR suggested that you should follow the gitflow, and also this is your second review after you did already get a first one in different Pr that you have merged, µI can suggest that you create another PR and add all the necessary elements to it then create a new PR that follow the gitflow rule, and again send for review**_

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MICHAELMUNAVU83** [comment]
Hello @dasileker  I wanted to ask what the problem is exactly because I worked on a different branch which i merged to dev then I submitted a link from dev to master.

**Comment by dasileker** [comment]
That's the first problem, you worked on the feature branch and got the review but you didn't ask another review in it instead you meged it and worked on the dev branch that's the second issue if you judt merged and created a new branch and submitted the PR of it, we will not invalidate it.

**Comment by MICHAELMUNAVU83** [comment]
@dasileker kindly advice what I should do because this is the capstone in which we submit the final link of the dev to the master

**Comment by MICHAELMUNAVU83** [comment]
I still submitted the link from the dev to the master

**Comment by dasileker** [comment]
I can advise on contacting the student success for this issue, and second you can creat a branch and add the work you have done then submit the PR WITH DETAILS that you have already submitted a different PR that has a review and this is an extension of it.

**Comment by MICHAELMUNAVU83** [comment]
@dasileker so the link that I will submit is the link of the new branch to the master or the dev?

**Comment by dasileker** [comment]
To the dev of course

**Pull request closed without merging**
